<html>
<head>
<title>500 Error</title>
<body>
<div>
<?php
echo "Yaf Caught exception : ";
?>
</div>
<div>
<?php foreach ($trace as $key => $value): ?>
	<p>
		<span><?php echo $key + 1; ?>.</span>
		Class:<?php echo $value['class'] ?? ''; ?>
		<span style="background-color:#FF6666 ;">
			Function:<?php echo $value['function'] ?? ''; ?>
		</span>
		Line:<?php echo $value['line'] ?? ''; ?>
		<br>
	</p>
<?php endforeach?>
<p style="background-color: #CCFFFF;"><?php echo $exception->getMessage() ?></p>
</body>
<html>